spring:
  application:
    name: bookapp

  datasource:
    url: jdbc:mysql://localhost:3306/alejandria?createDatabaseIfNotExist=true
    username: root
    password: solander10

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
